/* eslint-disable react/no-unknown-property */
/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import { useRef, useEffect } from "react";
import { useAnimations, useGLTF } from "@react-three/drei";
import { useFrame, useThree } from "@react-three/fiber";
import { a } from "@react-spring/three";

import IslandScene from "../assets/japan-island6.glb";

const Island = ({
  isRotating,
  setIsRotating,
  setCurrentStage,
  limitRotation,
  setLimitRotation,
  setIsMoving,
  isMoving,
  ...props
}) => {
  const islandRef = useRef();

  const { gl, viewport } = useThree();
  const { nodes, materials, animations } = useGLTF(IslandScene);
  const { actions } = useAnimations(animations, islandRef);

  const lastX = useRef(0);
  const lastY = useRef(0);
  const rotationSpeed = useRef(0);
  const dampingFactor = 0.95;

  const handlePointerDown = (e) => {
    e.stopPropagation();
    e.preventDefault();
    setIsRotating(true);
    setIsMoving(true);

    const clientX = event.touches ? event.touches[0].clientX : event.clientX;
    const clientY = event.touches ? event.touches[0].clientY : event.clientY;

    lastX.current = clientX;
    lastY.current = clientY;
  };
  const handlePointerUp = (e) => {
    e.stopPropagation();
    e.preventDefault();
    setIsRotating(false);
    if (Math.abs(rotationSpeed.current) < 0.12) setIsMoving(false);
  };
  const handlePointerMove = (e) => {
    e.stopPropagation();
    e.preventDefault();

    if (isRotating) {
      const clientX = event.touches ? event.touches[0].clientX : event.clientX;
      const clientY = event.touches ? event.touches[0].clientY : event.clientY;

      const deltaX = (clientX - lastX.current) / viewport.width;
      const deltaY = (clientY - lastY.current) / viewport.height;

      islandRef.current.rotation.y += deltaX * 0.01 * Math.PI;

      setLimitRotation(islandRef.current.rotation.x + deltaY * 0.01 * Math.PI);
      if (limitRotation <= 0.4 && limitRotation >= 0) {
        islandRef.current.rotation.x += deltaY * 0.01 * Math.PI;
      } else if (limitRotation > 0.4) islandRef.current.rotation.x = 0.4;
      else if (limitRotation < 0) islandRef.current.rotation.x = 0;

      lastX.current = clientX;
      lastY.current = clientY;
      rotationSpeed.current = deltaX * 0.01 * Math.PI;
    }
  };

  const handleKeyDown = (e) => {
    if (e.key == "ArrowLeft") {
      if (!isRotating) {
        setIsMoving(true);
        setIsRotating(true);
      }

      islandRef.current.rotation.y += 0.01 * Math.PI;
      rotationSpeed.current = 0.0125;
    } else if (e.key == "ArrowRight") {
      if (!isRotating) {
        setIsMoving(true);
        setIsRotating(true);
      }

      islandRef.current.rotation.y -= 0.01 * Math.PI;
      rotationSpeed.current = -0.0125;
    }
  };

  const handleKeyup = (e) => {
    if (e.key === "ArrowLeft" || e.key === "ArrowRight") {
      setIsRotating(false);
      setIsMoving(false);
    }
  };

  useFrame(() => {
    if (!isRotating && Math.abs(rotationSpeed.current) > 0) {
      if (Math.abs(rotationSpeed.current) < 0.01) setIsMoving(false);
    }
    if (!isRotating) {
      rotationSpeed.current *= dampingFactor;

      if (Math.abs(rotationSpeed.current) < 0.001) rotationSpeed.current = 0;

      islandRef.current.rotation.y += rotationSpeed.current;
    }

    if (isMoving || isRotating) {
      const rotation = islandRef.current.rotation.y;

      const normalizedRotation =
        ((rotation % (2 * Math.PI)) + 2 * Math.PI) % (2 * Math.PI);

      // Set the current stage based on the island's orientation
      switch (true) {
        case normalizedRotation >= 5.5 && normalizedRotation <= 6.1:
          setCurrentStage(5);
          break;
        case normalizedRotation >= 4.5 && normalizedRotation <= 5:
          setCurrentStage(4);
          break;
        case normalizedRotation >= 3.1 && normalizedRotation <= 3.8:
          setCurrentStage(3);
          break;
        case normalizedRotation >= 1.3 && normalizedRotation <= 2.5:
          setCurrentStage(2);
          break;
        case normalizedRotation >= 0.2 && normalizedRotation <= 0.8:
          setCurrentStage(1);
          break;
        default:
          setCurrentStage(null);
      }
    }
  });

  useEffect(() => {
    const canvas = gl.domElement;
    canvas.addEventListener("pointerdown", handlePointerDown);
    canvas.addEventListener("pointerup", handlePointerUp);
    canvas.addEventListener("pointermove", handlePointerMove);
    document.addEventListener("keydown", handleKeyDown);
    document.addEventListener("keyup", handleKeyup);

    return () => {
      canvas.removeEventListener("pointerdown", handlePointerDown);
      canvas.removeEventListener("pointerup", handlePointerUp);
      canvas.removeEventListener("pointermove", handlePointerMove);
      document.removeEventListener("keydown", handleKeyDown);
      document.removeEventListener("keyup", handleKeyup);
    };
  }, [gl, handlePointerDown, handlePointerUp, handlePointerMove]);

  useEffect(() => {
    actions["dron.004Action"].play();
    actions["dron.004Action.001"].play();
    actions["dron.004Action.002"].play();
    actions["dron.004Action.003"].play();
    actions["dronAction.001"].play();

    actions["signalAction"].play();

    actions["leaf.001Action"].play();
    actions["leaf.001Action.001"].play();
    actions["leaf.001Action.002"].play();
    actions["leaf.001Action.003"].play();
    actions["leaf.001Action.004"].play();
    actions["leaf.001Action.005"].play();
    actions["leaf.001Action.006"].play();
    actions["leaf.001Action.007"].play();
    actions["leaf.001Action.008"].play();
  }, []);

  return (
    <a.group ref={islandRef} {...props}>
      <group name="Scene">
        <group name="leaf-group">
          <mesh
            name="leaf"
            castShadow
            receiveShadow
            geometry={nodes.leaf.geometry}
            material={materials["Leaf-b-2"]}
          />
          <mesh
            name="leaf_1"
            castShadow
            receiveShadow
            geometry={nodes.leaf_1.geometry}
            material={materials["Leaf-b"]}
          />
          <mesh
            name="leaf_2"
            castShadow
            receiveShadow
            geometry={nodes.leaf_2.geometry}
            material={materials.OutLine}
          />
        </group>
        <group
          name="dron"
          position={[1.106, 1.786, 4.289]}
          rotation={[0.054, 0.47, -0.209]}
        >
          <mesh
            name="Cube075"
            castShadow
            receiveShadow
            geometry={nodes.Cube075.geometry}
            material={materials.Metal}
          />
          <mesh
            name="Cube075_1"
            castShadow
            receiveShadow
            geometry={nodes.Cube075_1.geometry}
            material={materials["Metal-2"]}
          />
          <mesh
            name="Cube075_2"
            castShadow
            receiveShadow
            geometry={nodes.Cube075_2.geometry}
            material={materials.OutLine}
          />
          <mesh
            name="dron001"
            castShadow
            receiveShadow
            geometry={nodes.dron001.geometry}
            material={materials.Black}
            position={[0.215, 0.028, 0.316]}
          />
          <mesh
            name="dron002"
            castShadow
            receiveShadow
            geometry={nodes.dron002.geometry}
            material={materials.Black}
            position={[0.356, -0.03, -0.138]}
          />
          <mesh
            name="dron003"
            castShadow
            receiveShadow
            geometry={nodes.dron003.geometry}
            material={materials.Black}
            position={[-0.212, 0.014, -0.32]}
          />
          <mesh
            name="dron004"
            castShadow
            receiveShadow
            geometry={nodes.dron004.geometry}
            material={materials.Black}
            position={[-0.353, 0.071, 0.134]}
          />
        </group>
        <group name="base001">
          <mesh
            name="Circle001"
            castShadow
            receiveShadow
            geometry={nodes.Circle001.geometry}
            material={materials.Land}
          />
          <mesh
            name="Circle001_1"
            castShadow
            receiveShadow
            geometry={nodes.Circle001_1.geometry}
            material={materials["Land-3"]}
          />
          <mesh
            name="Circle001_2"
            castShadow
            receiveShadow
            geometry={nodes.Circle001_2.geometry}
            material={materials["Land-2"]}
          />
          <mesh
            name="Circle001_3"
            castShadow
            receiveShadow
            geometry={nodes.Circle001_3.geometry}
            material={materials["Land-4"]}
          />
          <mesh
            name="Circle001_4"
            castShadow
            receiveShadow
            geometry={nodes.Circle001_4.geometry}
            material={materials.OutLine}
          />
          <group name="altar">
            <mesh
              name="Cube061"
              castShadow
              receiveShadow
              geometry={nodes.Cube061.geometry}
              material={materials.Rock}
            />
            <mesh
              name="Cube061_1"
              castShadow
              receiveShadow
              geometry={nodes.Cube061_1.geometry}
              material={materials["Rock-2"]}
            />
            <mesh
              name="Cube061_2"
              castShadow
              receiveShadow
              geometry={nodes.Cube061_2.geometry}
              material={materials.red}
            />
            <mesh
              name="Cube061_3"
              castShadow
              receiveShadow
              geometry={nodes.Cube061_3.geometry}
              material={materials.Black}
            />
            <mesh
              name="Cube061_4"
              castShadow
              receiveShadow
              geometry={nodes.Cube061_4.geometry}
              material={materials["Wood-door"]}
            />
            <mesh
              name="Cube061_5"
              castShadow
              receiveShadow
              geometry={nodes.Cube061_5.geometry}
              material={materials.OutLine}
            />
          </group>
          <group name="bamboo">
            <mesh
              name="Cylinder012"
              castShadow
              receiveShadow
              geometry={nodes.Cylinder012.geometry}
              material={materials.Bamboo}
            />
            <mesh
              name="Cylinder012_1"
              castShadow
              receiveShadow
              geometry={nodes.Cylinder012_1.geometry}
              material={materials["Wood-2"]}
            />
            <mesh
              name="Cylinder012_2"
              castShadow
              receiveShadow
              geometry={nodes.Cylinder012_2.geometry}
              material={materials.OutLine}
            />
          </group>
          <group name="box">
            <mesh
              name="Cube084"
              castShadow
              receiveShadow
              geometry={nodes.Cube084.geometry}
              material={materials.Box}
            />
            <mesh
              name="Cube084_1"
              castShadow
              receiveShadow
              geometry={nodes.Cube084_1.geometry}
              material={materials["Box.001"]}
            />
            <mesh
              name="Cube084_2"
              castShadow
              receiveShadow
              geometry={nodes.Cube084_2.geometry}
              material={materials.OutLine}
            />
          </group>
          <group name="chest">
            <mesh
              name="Circle005"
              castShadow
              receiveShadow
              geometry={nodes.Circle005.geometry}
              material={materials["Metal-2"]}
            />
            <mesh
              name="Circle005_1"
              castShadow
              receiveShadow
              geometry={nodes.Circle005_1.geometry}
              material={materials["red-2"]}
            />
            <mesh
              name="Circle005_2"
              castShadow
              receiveShadow
              geometry={nodes.Circle005_2.geometry}
              material={materials.OutLine}
            />
          </group>
          <mesh
            name="cube"
            castShadow
            receiveShadow
            geometry={nodes.cube.geometry}
            material={materials.Metal}
          />
          <group name="door">
            <mesh
              name="Cube042"
              castShadow
              receiveShadow
              geometry={nodes.Cube042.geometry}
              material={materials.Black}
            />
            <mesh
              name="Cube042_1"
              castShadow
              receiveShadow
              geometry={nodes.Cube042_1.geometry}
              material={materials.Orange}
            />
            <mesh
              name="Cube042_2"
              castShadow
              receiveShadow
              geometry={nodes.Cube042_2.geometry}
              material={materials.OutLine}
            />
          </group>
          <group name="feends">
            <mesh
              name="Circle030"
              castShadow
              receiveShadow
              geometry={nodes.Circle030.geometry}
              material={materials["Balcony-2"]}
            />
            <mesh
              name="Circle030_1"
              castShadow
              receiveShadow
              geometry={nodes.Circle030_1.geometry}
              material={materials.cable}
            />
          </group>
          <mesh
            name="grass"
            castShadow
            receiveShadow
            geometry={nodes.grass.geometry}
            material={materials["Leaf-2"]}
          />
          <group name="house">
            <mesh
              name="Cylinder006"
              castShadow
              receiveShadow
              geometry={nodes.Cylinder006.geometry}
              material={materials.Wood}
            />
            <mesh
              name="Cylinder006_1"
              castShadow
              receiveShadow
              geometry={nodes.Cylinder006_1.geometry}
              material={materials["Wood-door"]}
            />
            <mesh
              name="Cylinder006_2"
              castShadow
              receiveShadow
              geometry={nodes.Cylinder006_2.geometry}
              material={materials.Estructure}
            />
            <mesh
              name="Cylinder006_3"
              castShadow
              receiveShadow
              geometry={nodes.Cylinder006_3.geometry}
              material={materials["Balcony-2"]}
            />
            <mesh
              name="Cylinder006_4"
              castShadow
              receiveShadow
              geometry={nodes.Cylinder006_4.geometry}
              material={materials.Door}
            />
            <mesh
              name="Cylinder006_5"
              castShadow
              receiveShadow
              geometry={nodes.Cylinder006_5.geometry}
              material={materials.Roof}
            />
            <mesh
              name="Cylinder006_6"
              castShadow
              receiveShadow
              geometry={nodes.Cylinder006_6.geometry}
              material={materials.Balcony}
            />
            <mesh
              name="Cylinder006_7"
              castShadow
              receiveShadow
              geometry={nodes.Cylinder006_7.geometry}
              material={materials.Leaf}
            />
            <mesh
              name="Cylinder006_8"
              castShadow
              receiveShadow
              geometry={nodes.Cylinder006_8.geometry}
              material={materials["Estructure-2"]}
            />
            <mesh
              name="Cylinder006_9"
              castShadow
              receiveShadow
              geometry={nodes.Cylinder006_9.geometry}
              material={materials["Wood-2"]}
            />
            <mesh
              name="Cylinder006_10"
              castShadow
              receiveShadow
              geometry={nodes.Cylinder006_10.geometry}
              material={materials.Flowerpot}
            />
            <mesh
              name="Cylinder006_11"
              castShadow
              receiveShadow
              geometry={nodes.Cylinder006_11.geometry}
              material={materials["Leaf-2"]}
            />
            <mesh
              name="Cylinder006_12"
              castShadow
              receiveShadow
              geometry={nodes.Cylinder006_12.geometry}
              material={materials.Sing}
            />
            <mesh
              name="Cylinder006_13"
              castShadow
              receiveShadow
              geometry={nodes.Cylinder006_13.geometry}
              material={materials.Black}
            />
            <mesh
              name="Cylinder006_14"
              castShadow
              receiveShadow
              geometry={nodes.Cylinder006_14.geometry}
              material={materials["Leaf-b-2"]}
            />
            <mesh
              name="Cylinder006_15"
              castShadow
              receiveShadow
              geometry={nodes.Cylinder006_15.geometry}
              material={materials.Water}
            />
            <mesh
              name="Cylinder006_16"
              castShadow
              receiveShadow
              geometry={nodes.Cylinder006_16.geometry}
              material={materials.Land}
            />
            <mesh
              name="Cylinder006_17"
              castShadow
              receiveShadow
              geometry={nodes.Cylinder006_17.geometry}
              material={materials["Land-4"]}
            />
            <mesh
              name="Cylinder006_18"
              castShadow
              receiveShadow
              geometry={nodes.Cylinder006_18.geometry}
              material={materials["Wood-3"]}
            />
            <mesh
              name="Cylinder006_19"
              castShadow
              receiveShadow
              geometry={nodes.Cylinder006_19.geometry}
              material={materials.Metal}
            />
            <mesh
              name="Cylinder006_20"
              castShadow
              receiveShadow
              geometry={nodes.Cylinder006_20.geometry}
              material={materials.cable}
            />
            <mesh
              name="Cylinder006_21"
              castShadow
              receiveShadow
              geometry={nodes.Cylinder006_21.geometry}
              material={materials.red}
            />
            <mesh
              name="Cylinder006_22"
              castShadow
              receiveShadow
              geometry={nodes.Cylinder006_22.geometry}
              material={materials.Bamboo}
            />
            <mesh
              name="Cylinder006_23"
              castShadow
              receiveShadow
              geometry={nodes.Cylinder006_23.geometry}
              material={materials.glass}
            />
            <mesh
              name="Cylinder006_24"
              castShadow
              receiveShadow
              geometry={nodes.Cylinder006_24.geometry}
              material={materials["Metal-2"]}
            />
            <mesh
              name="Cylinder006_25"
              castShadow
              receiveShadow
              geometry={nodes.Cylinder006_25.geometry}
              material={materials.OutLine}
            />
          </group>
          <group name="land-2">
            <mesh
              name="Circle016"
              castShadow
              receiveShadow
              geometry={nodes.Circle016.geometry}
              material={materials["Land-6"]}
            />
            <mesh
              name="Circle016_1"
              castShadow
              receiveShadow
              geometry={nodes.Circle016_1.geometry}
              material={materials["Land-5"]}
            />
            <mesh
              name="Circle016_2"
              castShadow
              receiveShadow
              geometry={nodes.Circle016_2.geometry}
              material={materials.OutLine}
            />
          </group>
          <mesh
            name="rire"
            castShadow
            receiveShadow
            geometry={nodes.rire.geometry}
            material={materials.Balcony}
          />
          <group name="rock">
            <mesh
              name="Cube080"
              castShadow
              receiveShadow
              geometry={nodes.Cube080.geometry}
              material={materials["Rock-2"]}
            />
            <mesh
              name="Cube080_1"
              castShadow
              receiveShadow
              geometry={nodes.Cube080_1.geometry}
              material={materials.Rock}
            />
            <mesh
              name="Cube080_2"
              castShadow
              receiveShadow
              geometry={nodes.Cube080_2.geometry}
              material={materials.OutLine}
            />
          </group>
          <group name="rod" position={[0, 0, 0.351]}>
            <mesh
              name="Vert004"
              castShadow
              receiveShadow
              geometry={nodes.Vert004.geometry}
              material={materials["Wood-3"]}
            />
            <mesh
              name="Vert004_1"
              castShadow
              receiveShadow
              geometry={nodes.Vert004_1.geometry}
              material={materials.Metal}
            />
            <mesh
              name="Vert004_2"
              castShadow
              receiveShadow
              geometry={nodes.Vert004_2.geometry}
              material={materials["Metal-2"]}
            />
            <mesh
              name="Vert004_3"
              castShadow
              receiveShadow
              geometry={nodes.Vert004_3.geometry}
              material={materials["Balcony-2"]}
            />
          </group>
          <group name="signal">
            <mesh
              name="Circle013"
              castShadow
              receiveShadow
              geometry={nodes.Circle013.geometry}
              material={materials["Land-6"]}
            />
            <mesh
              name="Circle013_1"
              castShadow
              receiveShadow
              geometry={nodes.Circle013_1.geometry}
              material={materials.Orange}
            />
            <mesh
              name="Circle013_2"
              castShadow
              receiveShadow
              geometry={nodes.Circle013_2.geometry}
              material={materials.Black}
            />
            <mesh
              name="Circle013_3"
              castShadow
              receiveShadow
              geometry={nodes.Circle013_3.geometry}
              material={materials.Balcony}
            />
            <mesh
              name="Circle013_4"
              castShadow
              receiveShadow
              geometry={nodes.Circle013_4.geometry}
              material={materials["Wood-2"]}
            />
            <mesh
              name="Circle013_5"
              castShadow
              receiveShadow
              geometry={nodes.Circle013_5.geometry}
              material={materials.Sing}
            />
            <mesh
              name="Circle013_6"
              castShadow
              receiveShadow
              geometry={nodes.Circle013_6.geometry}
              material={materials.OutLine}
            />
          </group>
          <group name="sing">
            <mesh
              name="Cube"
              castShadow
              receiveShadow
              geometry={nodes.Cube.geometry}
              material={materials["Wood-door"]}
            />
            <mesh
              name="Cube_1"
              castShadow
              receiveShadow
              geometry={nodes.Cube_1.geometry}
              material={materials.glass}
            />
            <mesh
              name="Cube_2"
              castShadow
              receiveShadow
              geometry={nodes.Cube_2.geometry}
              material={materials.Estructure}
            />
            <mesh
              name="Cube_3"
              castShadow
              receiveShadow
              geometry={nodes.Cube_3.geometry}
              material={materials["Leaf-b"]}
            />
            <mesh
              name="Cube_4"
              castShadow
              receiveShadow
              geometry={nodes.Cube_4.geometry}
              material={materials["Metal-2"]}
            />
          </group>
          <group name="tree">
            <mesh
              name="Vert002"
              castShadow
              receiveShadow
              geometry={nodes.Vert002.geometry}
              material={materials["Wood-3"]}
            />
            <mesh
              name="Vert002_1"
              castShadow
              receiveShadow
              geometry={nodes.Vert002_1.geometry}
              material={materials.OutLine}
            />
          </group>
          <mesh
            name="Vert005"
            castShadow
            receiveShadow
            geometry={nodes.Vert005.geometry}
            material={materials.cable}
            position={[0, 0.425, 0.103]}
          />
          <mesh
            name="water"
            castShadow
            receiveShadow
            geometry={nodes.water.geometry}
            material={materials.Water}
          />
        </group>
        <group name="GPencil" />
        <mesh
          name="leaf001"
          castShadow
          receiveShadow
          geometry={nodes.leaf001.geometry}
          material={materials["Leaf-b"]}
          position={[1.714, 2.773, -4.84]}
          scale={0.8}
        />
        <mesh
          name="leaf002"
          castShadow
          receiveShadow
          geometry={nodes.leaf002.geometry}
          material={materials["Leaf-b"]}
          position={[2.206, 2.773, -4.84]}
        />
        <mesh
          name="leaf003"
          castShadow
          receiveShadow
          geometry={nodes.leaf003.geometry}
          material={materials["Leaf-b"]}
          position={[2.966, 2.14, -3.488]}
          scale={0.6}
        />
        <mesh
          name="leaf004"
          castShadow
          receiveShadow
          geometry={nodes.leaf004.geometry}
          material={materials["Leaf-b"]}
          position={[2.966, 2.14, -3.488]}
          scale={0.6}
        />
        <mesh
          name="leaf005"
          castShadow
          receiveShadow
          geometry={nodes.leaf005.geometry}
          material={materials["Leaf-b"]}
          position={[0.225, 3.357, -5.422]}
          scale={0.6}
        />
        <mesh
          name="leaf006"
          castShadow
          receiveShadow
          geometry={nodes.leaf006.geometry}
          material={materials["Leaf-b"]}
          position={[1.36, 3.357, -4.039]}
        />
        <mesh
          name="leaf007"
          castShadow
          receiveShadow
          geometry={nodes.leaf007.geometry}
          material={materials["Leaf-b"]}
          position={[0.05, 3.357, -5.038]}
        />
        <mesh
          name="leaf008"
          castShadow
          receiveShadow
          geometry={nodes.leaf008.geometry}
          material={materials["Leaf-b"]}
          position={[2.2, 2.122, -3.743]}
        />
        <mesh
          name="leaf009"
          castShadow
          receiveShadow
          geometry={nodes.leaf009.geometry}
          material={materials["Leaf-b"]}
          position={[1.852, 2.513, -3.724]}
          rotation={[-Math.PI, 1.32, -Math.PI]}
          scale={0.6}
        />
      </group>
    </a.group>
  );
};

export default Island;
